### ISSUE TITLE
Add Travis-CI support

### ISSUE THREAD

**Issue by StealthyLoner** [SLAMon/SLAMon#4]
Currently there is no continuous integration. All the tests need to be run manually. Adding support for Travis-CI would automate tests and possible future deployment to PyPI

**Comment by Korkkii** [comment]
Travis CI has been activated python agent, AFM, slamon-java-lib and jbpm repositories. The slamon-android will contain Travis CI when it is separated in [issue 2](https://github.com/SLAMon/SLAMon/issues/2)
